name: Product Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
            
      - name: Activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Digital Ocean Droplet
        uses: digitalocean/actions-doctl@v2
        with:
          doctl-version: 1.100.0
          doctl-context: default
          doctl-token: ${{ secrets.DO_TOKEN }}
          doctl-args: app deploy --app-name=currencyconverter --env=development